#! /usr/bin/env node

const fs = require('fs');
const path = require('path');

const indexContents = fs.readFileSync(path.join(__dirname, '../docs/index.html'), 'utf8');
const generatorContents = fs.readFileSync(path.join(__dirname, '../assets/generator.html'), 'utf8');

const indexContentsWithGenerator = indexContents.replace(
  '<!-- ALL-CONTRIBUTORS-BADGE:END -->',
  `<!-- ALL-CONTRIBUTORS-BADGE:END -->\n${generatorContents}`
);

fs.writeFileSync(path.join(__dirname, '../docs/index.html'), indexContentsWithGenerator);
